name: 🚀 Deploy Admin Panel to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  typecheck:
    name: 🔍 TypeScript Check
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
    
    - name: 🍞 Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: 📦 Install dependencies
      run: bun install
    
    - name: 🏗 Generate Prisma client
      run: bunx prisma generate
      env:
        DATABASE_URL: ${{ secrets.ADMIN_DATABASE_URL }}
    
    - name: 🔍 Type checking
      run: bun run typecheck
    
    - name: 🧹 Linting (continue on warning)
      run: bun run lint || true

  build:
    name: 🏗 Build Admin Panel
    runs-on: ubuntu-latest
    needs: typecheck
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
    
    - name: 🍞 Setup Bun  
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: 📦 Install dependencies
      run: bun install
    
    - name: 🏗 Generate Prisma client
      run: bunx prisma generate
      env:
        DATABASE_URL: ${{ secrets.ADMIN_DATABASE_URL }}
    
    - name: 🏗 Build Next.js application
      run: bunx next build
      env:
        DATABASE_URL: ${{ secrets.ADMIN_DATABASE_URL }}
        NEXTAUTH_SECRET: ${{ secrets.ADMIN_NEXTAUTH_SECRET }}
        NEXTAUTH_URL: ${{ secrets.ADMIN_NEXTAUTH_URL }}
        AUTH_TRUST_HOST: ${{ secrets.ADMIN_AUTH_TRUST_HOST }}
        AUTH_YANDEX_ID: ${{ secrets.ADMIN_AUTH_YANDEX_ID }}
        AUTH_YANDEX_SECRET: ${{ secrets.ADMIN_AUTH_YANDEX_SECRET }}
        EMAIL_SERVER_HOST: ${{ secrets.ADMIN_EMAIL_SERVER_HOST }}
        EMAIL_SERVER_PORT: ${{ secrets.ADMIN_EMAIL_SERVER_PORT }}
        EMAIL_SERVER_USER: ${{ secrets.ADMIN_EMAIL_SERVER_USER }}
        EMAIL_SERVER_PASSWORD: ${{ secrets.ADMIN_EMAIL_SERVER_PASSWORD }}
        EMAIL_FROM: ${{ secrets.ADMIN_EMAIL_FROM }}
        GROQ_API_KEY: ${{ secrets.ADMIN_GROQ_API_KEY }}
        GROQ_MODEL: ${{ secrets.ADMIN_GROQ_MODEL }}
        AI_PROVIDER: ${{ secrets.ADMIN_AI_PROVIDER }}
        PORT: ${{ secrets.ADMIN_PORT }}
    
    - name: 📦 Create deployment package
      run: |
        mkdir -p deploy
        
        echo "Проверяем наличие файлов для деплоя:"
        ls -la
        
        # Копируем обязательные файлы
        if [ -d ".next" ]; then
          cp -r .next deploy/
          echo "✅ .next скопирован"
        else
          echo "❌ .next не найден!"
          exit 1
        fi
        
        if [ -d "public" ]; then
          cp -r public deploy/
          echo "✅ public скопирован"
        else
          echo "⚠️ public не найден, пропускаем"
        fi
        
        if [ -f "package.json" ]; then
          cp package.json deploy/
          echo "✅ package.json скопирован"
        else
          echo "❌ package.json не найден!"
          exit 1
        fi
        
        # Копируем lockfile
        if [ -f "bun.lock" ]; then
          cp bun.lock deploy/
          echo "✅ bun.lock скопирован"
        elif [ -f "yarn.lock" ]; then
          cp yarn.lock deploy/
          echo "✅ yarn.lock скопирован"
        elif [ -f "package-lock.json" ]; then
          cp package-lock.json deploy/
          echo "✅ package-lock.json скопирован"
        else
          echo "⚠️ Lockfile не найден"
        fi
        
        if [ -d "prisma" ]; then
          cp -r prisma deploy/
          echo "✅ prisma скопирован"
        else
          echo "❌ prisma не найден!"
          exit 1
        fi
        
        if [ -f "ecosystem.admin.config.cjs" ]; then
          cp ecosystem.admin.config.cjs deploy/
          echo "✅ ecosystem.admin.config.cjs скопирован"
        else
          echo "❌ ecosystem.admin.config.cjs не найден!"
          exit 1
        fi
        
        echo "Финальное содержимое deploy:"
        ls -la deploy/
        
    - name: 📤 Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: admin-build
        path: deploy/
        retention-days: 1

  deploy:
    name: 🚀 Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: 📥 Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: admin-build
        path: ./deploy
    
    - name: 🔑 Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ADMIN_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.ADMIN_DEPLOY_HOST }} >> ~/.ssh/known_hosts
    
    - name: 🚀 Deploy to server
      run: |
        # Проверяем содержимое deploy директории
        echo "Содержимое deploy директории:"
        ls -la deploy/
        
        # Создаем архив для передачи
        cd deploy
        echo "Создаем архив..."
        tar -czf ../admin-deploy.tar.gz .
        cd ..
        
        # Проверяем, что архив создался
        if [ -f "admin-deploy.tar.gz" ]; then
          echo "✅ Архив создан успешно, размер: $(du -h admin-deploy.tar.gz | cut -f1)"
        else
          echo "❌ Ошибка: архив не создан!"
          exit 1
        fi
        
        # Копируем на сервер с проверкой
        echo "Копируем архив на сервер..."
        scp -o StrictHostKeyChecking=no -v admin-deploy.tar.gz ${{ secrets.ADMIN_DEPLOY_USER }}@${{ secrets.ADMIN_DEPLOY_HOST }}:/tmp/
        
        # Проверяем, что файл скопировался на сервер
        ssh -o StrictHostKeyChecking=no ${{ secrets.ADMIN_DEPLOY_USER }}@${{ secrets.ADMIN_DEPLOY_HOST }} "ls -la /tmp/admin-deploy.tar.gz"
        
        # Предварительная очистка на сервере (БЕЗ /tmp)
        ssh -o StrictHostKeyChecking=no ${{ secrets.ADMIN_DEPLOY_USER }}@${{ secrets.ADMIN_DEPLOY_HOST }} << 'EOF'
          set -e
          
          # Очистка старых бэкапов (оставляем только последние 2)
          echo "Очищаем старые бэкапы..."
          find /var/www -name "admin.kirdro.ru.backup.*" -type d | sort | head -n -2 | xargs -r sudo rm -rf
          
          # Очистка кеша и var/tmp (НЕ трогаем /tmp)
          echo "Очищаем кеш и временные файлы (кроме /tmp)..."
          sudo rm -rf /var/tmp/* 2>/dev/null || true
          
          # Очистка node_modules в других проектах если есть
          echo "Очищаем node_modules в других проектах..."
          find /var/www -name "node_modules" -type d ! -path "*/admin.kirdro.ru/*" | head -5 | xargs -r sudo rm -rf
          
          # Очистка логов старше 7 дней
          echo "Очищаем старые логи..."
          find /var/log -name "*.log" -mtime +7 -exec sudo rm {} \; 2>/dev/null || true
          
          # Проверяем свободное место
          echo "Свободное место после очистки:"
          df -h /
        EOF
        
        # Основное развертывание приложения
        ssh -o StrictHostKeyChecking=no ${{ secrets.ADMIN_DEPLOY_USER }}@${{ secrets.ADMIN_DEPLOY_HOST }} << 'EOF'
          set -e
          
          # Проверяем наличие архива на сервере
          if [ ! -f "/tmp/admin-deploy.tar.gz" ]; then
            echo "❌ Ошибка: архив /tmp/admin-deploy.tar.gz не найден на сервере!"
            exit 1
          fi
          
          echo "📦 Архив найден на сервере, размер: $(du -h /tmp/admin-deploy.tar.gz | cut -f1)"
          
          # Backup предыдущей версии
          if [ -d "/var/www/admin.kirdro.ru" ]; then
            sudo cp -r /var/www/admin.kirdro.ru /var/www/admin.kirdro.ru.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
          fi
          
          # Создаем директорию если не существует
          sudo mkdir -p /var/www/admin.kirdro.ru
          sudo chown -R $USER:$USER /var/www/admin.kirdro.ru
          
          # Переходим в директорию и очищаем старые файлы
          cd /var/www/admin.kirdro.ru
          find . -mindepth 1 -delete 2>/dev/null || true
          
          # Распаковываем новую версию
          echo "📂 Распаковываем архив..."
          tar -xzf /tmp/admin-deploy.tar.gz -C /var/www/admin.kirdro.ru/
          
          # Проверяем наличие файлов после распаковки
          echo "Содержимое после распаковки:"
          ls -la
          
          # Создаем .env файл с продакшн переменными
          cat > /var/www/admin.kirdro.ru/.env << 'ENVEOF'
        DATABASE_URL="${{ secrets.ADMIN_DATABASE_URL }}"
        NEXTAUTH_SECRET="${{ secrets.ADMIN_NEXTAUTH_SECRET }}"
        NEXTAUTH_URL="${{ secrets.ADMIN_NEXTAUTH_URL }}"
        AUTH_SECRET="${{ secrets.ADMIN_AUTH_SECRET }}"
        AUTH_TRUST_HOST="${{ secrets.ADMIN_AUTH_TRUST_HOST }}"
        AUTH_YANDEX_ID="${{ secrets.ADMIN_AUTH_YANDEX_ID }}"
        AUTH_YANDEX_SECRET="${{ secrets.ADMIN_AUTH_YANDEX_SECRET }}"
        EMAIL_SERVER_HOST="${{ secrets.ADMIN_EMAIL_SERVER_HOST }}"
        EMAIL_SERVER_PORT="${{ secrets.ADMIN_EMAIL_SERVER_PORT }}"
        EMAIL_SERVER_USER="${{ secrets.ADMIN_EMAIL_SERVER_USER }}"
        EMAIL_SERVER_PASSWORD="${{ secrets.ADMIN_EMAIL_SERVER_PASSWORD }}"
        EMAIL_FROM="${{ secrets.ADMIN_EMAIL_FROM }}"
        GROQ_API_KEY="${{ secrets.ADMIN_GROQ_API_KEY }}"
        GROQ_MODEL="${{ secrets.ADMIN_GROQ_MODEL }}"
        AI_PROVIDER="${{ secrets.ADMIN_AI_PROVIDER }}"
        NODE_ENV=production
        PORT=3004
        ENVEOF
          
          # Устанавливаем зависимости с правильными правами и оптимизацией
          cd /var/www/admin.kirdro.ru
          export HOME=/home/$USER
          
          # Очищаем кеш bun перед установкой
          rm -rf ~/.cache/bun 2>/dev/null || true
          
          # Устанавливаем только продакшн зависимости без кеша
          bun install --production --no-cache
          
          # Генерируем Prisma клиент
          export DATABASE_URL="${{ secrets.ADMIN_DATABASE_URL }}"
          bunx prisma generate
          
          # Настраиваем права
          sudo chown -R $USER:$USER /var/www/admin.kirdro.ru
          chmod 600 .env
          
          # Перезапускаем через PM2
          pm2 reload admin-kirdro-portfolio || pm2 start ecosystem.admin.config.cjs
          
          # Ждем запуска приложения
          sleep 10
          
          # Cleanup временных файлов
          rm -f /tmp/admin-deploy.tar.gz
          
          # Очистка /tmp только ПОСЛЕ использования архива
          echo "Очищаем /tmp (кроме системных файлов)..."
          find /tmp -type f -name "*.tar.gz" -delete 2>/dev/null || true
          find /tmp -type f -name "*.tmp" -delete 2>/dev/null || true
          find /tmp -type f -name "*.log" -delete 2>/dev/null || true
          
          # Финальная очистка кеша npm/bun если есть
          rm -rf ~/.cache/bun 2>/dev/null || true
          rm -rf ~/.npm/_cacache 2>/dev/null || true
          
          # Проверяем финальное использование диска
          echo "Финальное использование диска:"
          df -h /
          
          echo "✅ Деплой админ-панели завершен успешно!"
        EOF

  health-check:
    name: 🩺 Health Check
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: 🏥 Check API Health
      run: |
        echo "🔍 Проверяем health check API..."
        
        # Ждем полной загрузки приложения
        sleep 15
        
        # Проверяем API health endpoint
        for i in {1..5}; do
          echo "Попытка $i/5..."
          if curl -f -s "https://admin.kirdro.ru/api/health" > /tmp/health.json; then
            echo "✅ Health check API работает!"
            cat /tmp/health.json | jq '.'
            break
          else
            echo "❌ Health check не отвечает, ждем 10 секунд..."
            sleep 10
          fi
          
          if [ $i -eq 5 ]; then
            echo "🚨 Health check не прошел после 5 попыток!"
            exit 1
          fi
        done
    
    - name: 🌐 Check Main Page
      run: |
        echo "🔍 Проверяем главную страницу..."
        
        # Проверяем главную страницу
        if curl -f -s -I "https://admin.kirdro.ru/" | grep "200 OK"; then
          echo "✅ Главная страница доступна!"
        else
          echo "❌ Главная страница недоступна!"
          
          # Диагностика при ошибке
          echo "🔍 Диагностика на сервере:"
          ssh -o StrictHostKeyChecking=no ${{ secrets.ADMIN_DEPLOY_USER }}@${{ secrets.ADMIN_DEPLOY_HOST }} << 'EOF'
            echo "PM2 статус:"
            pm2 status admin-kirdro-portfolio
            echo "Логи PM2:"
            pm2 logs admin-kirdro-portfolio --lines 20
            echo "Проверка порта 3004:"
            netstat -tlnp | grep :3004
          EOF
          
          exit 1
        fi
    
    - name: 🎉 Success Notification
      run: |
        echo "🎉 Деплой админ-панели admin.kirdro.ru успешно завершен!"
        echo "🌐 Доступно по адресу: https://admin.kirdro.ru"
        echo "🩺 Health Check: https://admin.kirdro.ru/api/health"